# https://andyrusiecki.dev/posts/fedora-silverblue-docker-compose/
version: '3'
services:
  zomboid:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PASSWORD: "CHANGEME"
    ports:
      - "16261:16261/udp"
    volumes:
      # Z to configure SELinux to ensure only one container can access this directory at once
      # Set game install directory
      - "./game_files:/install_dir:Z"
      # Set game savefile directory
      - "./saves:/root/Zomboid:Z"
      # set game log output directory
      - "./logs:/root/Steam/logs:Z"